spring:
  datasource:
    url: jdbc:mysql://server:3306/casinos?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: it123456
  redis:
    host: server