spring:
  datasource:
    url: jdbc:mysql://localhost:3306/casinos?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: !QAZ2WSX3EDC
  redis:
    host: localhost
